### ISSUE TITLE
Xbox one issues with Towerfall 8-Player (official)

### ISSUE THREAD

**Issue by nonobio** [Jonesey13/TF-8-Player#5]
​Hi,

I just bought Towerfall 8-players.

I know this github is for an unofficial mod but maybe you have an idea of my issue:

​I have some issues with Xbox One controllers :
X and B buttons are switched.
Right trigger (dodge/catch) doesn't work when used in wireless.
With Towerfall original (STeam), iall is working fine. 

​Do you know what could be the cause ?
Thanks

**Comment by Sawtaytoes** [comment]
If you want 8-players, there's an official 8-player build on Itch.io from the creator:
https://mattmakesgames.itch.io/towerfall-8-player

This one is in widescreen as well!

**Comment by nonobio** [comment]
Hi,


It is the one i bought ;) .

I managed to create two configs files (one for wire and one for wireless) that works :) .

For resume :
With Xbox One gamepad wireless and wire : X and B was switched (game related issue i think).
With Xbox One gamepad wireless only : right trigger (Dodge in Towerfall) didn't work (windows driver related issue à think because i can see a different action -Z axis- in joy.cpl).

So i created two file :
A Xbox OneWireless.xml that just a copy of the original Xbox360 but with ID of my Xbox One pad. 
A Xbox OneFil.xml : the same + two lines for the trigger roght (id 5) assigned to Dodge.

Everything is almost working (my Wireless adaptator for Windows 1713 crash sometimes but it is another story...).

If someone is interested :

[20210414_TowerFall_Gamepad_Config_XboxOne.zip](https://1drv.ms/u/s!Aj0j3I6ZhtiGgecoXd-ciuXvYSw-bQ?e=5Adr7s)

Bye
